service: vttc

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

functions:
  authorize:
    handler: handler.authorize
  login:
    handler: handler.login
    events:
      - http:
          path: /login
          method: post
          cors: true
  api:
    handler: handler.api
    events:
      - http:
          path: /
          method: get
          cors: true
  admin:
    handler: handler.admin
    events:
      - http:
          path: /
          method: post
          cors: true
          authorizer: authorize

plugins:
  - serverless-offline