service: vttc

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

functions:
  convert:
    handler: handler.convert
    events:
      - http:
          path: /
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin