service: vttc

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

functions:
  cdupload:
    handler: handler.cdupload
    timeout: 60
    memorySize: 512
    events:
      - http:
          path: /
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin